[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"

[package]
name = "tokeniser-api"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8.2"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.140"
tokenizers = { version = "0.21.0", features = ["http"] }
tokio = { version = "1.43.0", features = ["full"] }
tower-http = { version = "0.6.2", features = ["util"] }
utoipa = { version = "5.3.1", features = ["axum_extras"] }
utoipa-swagger-ui = { version = "9.0.0", features = ["axum"] }
utoipauto = "0.2.0"

[dev-dependencies]
anyhow = "1.0.97"
axum-test = "17.2.0"
