[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"

[package]
name = "tokeniser-api"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.7"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.132"
tokenizers = { version = "0.20.1", features = ["http"] }
tokio = { version = "1.40.0", features = ["full"] }
tower-http = { version = "0.6.1", features = ["util"] }
utoipa = { version = "5.1.1", features = ["axum_extras"] }
utoipa-swagger-ui = { version = "8.0.1", features = ["axum"] }
utoipauto = "0.2.0"

[dev-dependencies]
anyhow = "1.0.90"
axum-test = "15.3.1"
