FROM rust:slim AS rust-builder

COPY . .

RUN apt update
RUN apt install -y pkg-config libssl-dev g++ curl
RUN rustup default nightly
RUN cargo install --locked --path .


FROM python:slim

ENV HOME=/home/user
ENV PATH=$HOME/app:$PATH

RUN useradd -m -u 1000 user

USER user

WORKDIR $HOME/app

COPY --chown=user --from=rust-builder   /target/release/tokeniser-api $HOME/app

CMD ["tokeniser-api"]
