name: Build

on:
  push:
    branches: main
    paths:
      - .github/workflows/main.yml
      - Dockerfile.build
      - Cargo.toml
      - src/**

jobs:
  rust:
    uses: winstxnhdw/actions/.github/workflows/rust.yml@main
